apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dpd-net-be
  namespace: dpd-be-ns
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels: {}
        namespaceSelector:
          matchLabels:
            tier: istio
    - from:
      - ipBlock:
          cidr: 192.168.0.135/32
  egress:
    - to:
      - podSelector:
          matchLabels: {}
        namespaceSelector:
          matchLabels:
            tier: istio
    - to:
      - ipBlock:
          cidr: 192.168.0.135/32
    # S3 
    # - to:
    #   - ipBlock:
    #       cidr: 0.0.0.0/0  
    # - to:
    #   - podSelector:
    #       matchLabels: {}
    #     namespaceSelector:
    #       matchLabels:
    #         tier: dpd-rmq-ns
    # - to:
    #   - podSelector:
    #       matchLabels: {}
    #     namespaceSelector:
    #       matchLabels:
    #         tier: dpd-fe-ns
    # - to:
    #   - podSelector:
    #       matchLabels: {}
    #     namespaceSelector:
    #       matchLabels:
    #         kubernetes.io/metadata.name: kube-system
    #     podSelector:
    #       matchLabels:
    #         k8s-app: kube-dns
