apiVersion: v1
kind: PersistentVolume
metadata:
  name: dpd-rmq-pv
  namespace: dpd-rmq-ns
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rabbitmq
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dpd-rmq-pvc
  namespace: dpd-rmq-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
