apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dpd-fe-ns
  name: kms-fe-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]
