apiVersion: v1
kind: Service
metadata:
  name: dpd-be-spring-svc
  namespace: dpd-be-ns
  labels:
    app: dpd-be-spring-svc
spec:
  selector:
    app: dpd-be-spring-dep
  type: NodePort # type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
